name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Go"]
    types: [completed]

jobs:

  on-success:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fizzbuzz:$(date +%s)
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
