name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      ci:
        description: "CI pipeline"
        required: false
        default: "go.yml"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Abort if CI not successful
      if: steps.check.outputs.status != 'success'
      run: |
        echo ${{ steps.check.outputs.status }}
        exit 1
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fizzbuzz:$(date +%s)
