name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
  
    env:
      GIN_MODE: release
        
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get Swag command
      run: go get -u github.com/swaggo/swag/cmd/swag

    - name: Swagger
      run: swag init -d cmd/fizzbuzz/ --parseDependency

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        GIN_MODE: release
